version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: information on sales, order, product and date
        columns:
          - name: orders_id
          - name: pdt_id
        tests:
          - unique:
              column_name: "(orders_id || '_' || pdt_id)"
          
      - name: product
        identifier: raw_gz_product
        description: information sur le prix d'acahat
        columns:
          - name: products_id
            description: primary key of the table
            tests:
              - unique
              - not_null
                  
      - name: ship
        identifier: raw_gz_ship
        description: couts d'envoit
        columns:
          - name: orders_id
            description: primary key of the table
            tests:
              - unique
              - not_null
                  
             