version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: information on sales, order, product and date
        columns:
          - name: orders_id
          - name: pdt_id
        tests:
          - unique:
              column_name: "(orders_id || '_' || pdt_id)"

      - name: product
        identifier: raw_gz_product
        description: information sur le prix d'acahat
        columns:
          - name: products_id
            description: primary key of the table
            tests:
              - unique
              - not_null

      - name: ship
        identifier: raw_gz_ship
        description: couts d'envoit
        columns:
          - name: orders_id
            description: primary key of the table
            tests:
              - unique
              - not_null

      - name: adwords
        identifier: raw_gz_adwords
        description: google analytics
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click

      - name: bing
        identifier: raw_gz_bing
        description: microsoft pub
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click

      - name: criteo
        identifier: raw_gz_criteo
        description: agence pub multimedia
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click

      - name: facebook
        identifier: raw_gz_facebook
        description: pub facebook
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click

models:
  - name: int_campaigns
    tests: 
      - unique:
          column_name: "(date_date || '_' || campaign_key)"
  - name: int_campaigns_day
    description: agrégation ads campaign par jour
    columns: 
      - name: date_date
        tests:
            - unique
            - not_null
      - name: ads_cost
      - name: ads_impressions
      - name: ads_clicks

